# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sokolská župa Barákova
description: > # this means to ignore newlines until "baseurl:"
  Organizace zaštiťující činnost tělocvičných jednot Sokol ve východní části Středočeského kraje.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.zbarakova.cz" # the base hostname & protocol for your site

defaults:
   - scope:
       path: ""
       type: posts
     values:
       layout: post

future: true

timezone: Europe/Prague

# Build settings
markdown: kramdown